application: pay-tool
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /static
  expiration: 1d
  static_dir: static
- url: /lib
  expiration: 7d
  static_dir: lib
- url: /.*
  script: main.app