application: pay-tool
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /(robots\.txt)
  static_files: \1
  upload: (robots\.txt)
- url: /static
  expiration: 1d
  static_dir: static
- url: /lib
  expiration: 7d
  static_dir: lib
- url: /.*
  script: main.app